// Mock data — only NotificationsPage still uses mock data (no backend campaign endpoints yet)

export const mockNotifications = [
  { _id: '1', title: 'New Year Sale is Live!', body: 'Get 30% off on all theory packages. Limited time offer!', type: 'promotional' as const, target: 'all' as const, target_count: 1200, sent_at: '2026-01-01T09:00:00Z', delivered_count: 1150, read_count: 780, click_count: 342, status: 'delivered' as const, channel: 'push' as const, created_by: 'Super Admin' },
  { _id: '2', title: 'Live Session Tomorrow', body: 'Dr. Priya Sharma - Upper Limb Anatomy at 10:30 AM', type: 'reminder' as const, target: 'segment' as const, target_count: 85, sent_at: '2026-02-14T18:00:00Z', delivered_count: 82, read_count: 68, click_count: 45, status: 'delivered' as const, channel: 'push' as const, created_by: 'Content Manager' },
  { _id: '3', title: 'Payment Received', body: 'Your payment of ₹3,999 for Anatomy Theory Complete has been received', type: 'transactional' as const, target: 'individual' as const, target_count: 1, sent_at: '2026-01-10T08:05:00Z', delivered_count: 1, read_count: 1, click_count: 0, status: 'delivered' as const, channel: 'push' as const, created_by: 'System' },
  { _id: '4', title: 'Complete Your Profile', body: 'Your profile is 30% complete. Add your details to get personalized recommendations.', type: 'engagement' as const, target: 'segment' as const, target_count: 45, sent_at: '2026-02-08T10:00:00Z', delivered_count: 40, read_count: 12, click_count: 8, status: 'delivered' as const, channel: 'push' as const, created_by: 'Content Manager' },
  { _id: '5', title: 'New Video: Nerve Supply of Forearm', body: 'A new video has been uploaded by Dr. Priya Sharma. Watch now!', type: 'content' as const, target: 'segment' as const, target_count: 234, sent_at: '2026-02-12T09:00:00Z', delivered_count: 220, read_count: 156, click_count: 98, status: 'delivered' as const, channel: 'push' as const, created_by: 'Content Manager' },
  { _id: '6', title: 'Subscription Expiring Soon', body: 'Your Physiology Theory subscription expires in 7 days. Renew now to continue learning.', type: 'reminder' as const, target: 'segment' as const, target_count: 28, sent_at: '2026-02-11T08:00:00Z', delivered_count: 26, read_count: 18, click_count: 10, status: 'delivered' as const, channel: 'push' as const, created_by: 'System' },
  { _id: '7', title: 'Flash Sale: Biochemistry Crash Course', body: 'Only ₹1,499! Offer valid till Feb 28.', type: 'promotional' as const, target: 'all' as const, target_count: 1200, sent_at: null, delivered_count: 0, read_count: 0, click_count: 0, status: 'scheduled' as const, channel: 'push' as const, created_by: 'Super Admin', scheduled_for: '2026-02-15T09:00:00Z' },
  { _id: '8', title: 'Session Cancelled: Biochemistry Rapid Fire', body: 'The scheduled session has been cancelled. We apologize for the inconvenience.', type: 'transactional' as const, target: 'segment' as const, target_count: 15, sent_at: '2026-02-12T10:00:00Z', delivered_count: 14, read_count: 14, click_count: 0, status: 'delivered' as const, channel: 'push' as const, created_by: 'System' },
]
